@server = http://localhost:4004
@auth = Authorization: Basic alice:


### MUser
# @name MUser_GET
GET {{server}}/odata/v4/generic/MUser
{{auth}}


### MUser
# @name MUser_POST
POST {{server}}/odata/v4/generic/MUser
Content-Type: application/json
{{auth}}

{
  "UserID": "22654219-64cb-4ee6-985f-47237c9510d4",
  "Username": "Username-22654219",
  "Usercode": "Usercode-22654219",
  "UserDept": {
    "UserDepartmentID": "3862361e-bcff-489a-b18b-c7b3df9ae8fd"
  },
  "createdAt": "2010-07-15T00:00:00.000Z",
  "createdBy": "createdBy.dhk3v@example.org",
  "modifiedAt": "2010-06-12T00:00:00.000Z",
  "modifiedBy": "modifiedBy.dhk3v@example.org"
}


### MUser
# @name MUser_PATCH
PATCH {{server}}/odata/v4/generic/MUser/22654219-64cb-4ee6-985f-47237c9510d4
Content-Type: application/json
{{auth}}

{
  "UserID": "22654219-64cb-4ee6-985f-47237c9510d4",
  "Username": "Username-22654219",
  "Usercode": "Usercode-22654219",
  "UserDept": {
    "UserDepartmentID": "3862361e-bcff-489a-b18b-c7b3df9ae8fd"
  },
  "createdAt": "2010-07-15T00:00:00.000Z",
  "createdBy": "createdBy.dhk3v@example.org",
  "modifiedAt": "2010-06-12T00:00:00.000Z",
  "modifiedBy": "modifiedBy.dhk3v@example.org"
}


### MUser
# @name MUser_DELETE
DELETE {{server}}/odata/v4/generic/MUser/22654219-64cb-4ee6-985f-47237c9510d4
Content-Type: application/json
{{auth}}


### MDepartment
# @name MDepartment_GET
GET {{server}}/odata/v4/generic/MDepartment
{{auth}}


### MDepartment
# @name MDepartment_POST
POST {{server}}/odata/v4/generic/MDepartment
Content-Type: application/json
{{auth}}

{
  "UserDepartmentID": "3862361e-bcff-489a-b18b-c7b3df9ae8fd",
  "DepartmentName": "DepartmentName-3862361",
  "UserID": {
    "UserID": "22654219-64cb-4ee6-985f-47237c9510d4"
  },
  "createdAt": "2013-07-20T00:00:00.000Z",
  "createdBy": "createdBy.2as7t@example.org",
  "modifiedAt": "2020-09-07T00:00:00.000Z",
  "modifiedBy": "modifiedBy.2as7t@example.org"
}


### MDepartment
# @name MDepartment_PATCH
PATCH {{server}}/odata/v4/generic/MDepartment/3862361e-bcff-489a-b18b-c7b3df9ae8fd
Content-Type: application/json
{{auth}}

{
  "UserDepartmentID": "3862361e-bcff-489a-b18b-c7b3df9ae8fd",
  "DepartmentName": "DepartmentName-3862361",
  "UserID": {
    "UserID": "22654219-64cb-4ee6-985f-47237c9510d4"
  },
  "createdAt": "2013-07-20T00:00:00.000Z",
  "createdBy": "createdBy.2as7t@example.org",
  "modifiedAt": "2020-09-07T00:00:00.000Z",
  "modifiedBy": "modifiedBy.2as7t@example.org"
}


### MDepartment
# @name MDepartment_DELETE
DELETE {{server}}/odata/v4/generic/MDepartment/3862361e-bcff-489a-b18b-c7b3df9ae8fd
Content-Type: application/json
{{auth}}
