@server = http://localhost:4004
@auth = Authorization: Basic alice:


### Employees
# @name Employees_GET
GET {{server}}/odata/v4/employee/Employees
{{auth}}


### Employees
# @name Employees_POST
POST {{server}}/odata/v4/employee/Employees
Content-Type: application/json
{{auth}}

{
  "ID": 6400010,
  "Name": "Name-64009",
  "Age": 37,
  "Salary": 6904533.15
}


### Employees
# @name Employees_PATCH
PATCH {{server}}/odata/v4/employee/Employees/7687
Content-Type: application/json
{{auth}}

{
  "ID": 649009,
  "Name": "Name-64009",
  "Age": 37,
  "Salary": 69049.15
}


### Employees
# @name Employees_DELETE
DELETE {{server}}/odata/v4/employee/Employees/7687
Content-Type: application/json
{{auth}}
