using {db} from '../db/employee';

service EmployeeService {
    entity Employees as projection on db.Employee;
    entity MUser     as projection on db.User;
    entity MDepartment     as projection on db.UserDepartment;
    entity GetVehicleDetail as projection on db.ZVT_ANPR_REC{
        ZUID              AS ZUID,
        WERKS             AS SiteId,
        ZLANE             AS SectionId,
        ZCAPDATE          AS CapturedOn,
        ZVPLATEN          AS VehPlateNo,
        ZVPLATES          AS VehPlateSource,
        ZVPLATESD         AS VehPlateSourceDesc,
        ZVPLATEC          AS VehPLateColor,
        ZVPLATECD         AS VehPLateColorDesc,
        ZVPLATEK          AS VehPLateKind,
        ZVPLATEKD         AS VehPlateKindDesc,
        ZVPLATET          AS VehPLateType,
        ZVPLATETD         AS VehPlateTypeDesc,
        ZVPLATEP          AS VehPLatePicture, //Ask From Pradeep sir 
        ZANPRCN           AS CameraNumber,
        ZAVERSION         AS AppVersionNumber,
        ZAPPNAME          AS AppName,
        ZRECTIME          AS ZRECTIME,
        ZUSEDFLAG         AS ZUSEDFLAG   
    }
    entity SITELANEANPR     as projection on db.ZSD_T_VI_SITELANEANPR;
   entity GetVehicleDetails as projection on db.ZSD_T_VEHICLE {
    zVehicleId               AS  VehicleDetail_Id,
    zPlateNo                 AS  PlateNumber,
    zPlateSourceModel        AS  PlateourceCode,
    zPlateSource             AS  PlateSource,
    zPlateSourceAE           AS  PLateSourceArabic,
    zPlateColorCode          AS  PLateColorCode,
    zPlateColor              AS  PlateColor,
    zPlateColorAE            AS  PlateColorArabic,
    zPlateKindCode           AS  PlateKindCode,
    zPlateKindEA             AS  PlateKindArabic,
    zPlateTypeCode           AS  PlateTypeCode,
    zPlateType               AS  PlateType,
    zPlateTypeAE             AS  PlateTypeArabic,
    zKindCode                AS  PlateKind,
    zKind                    AS  Kind,
    zKindAE                  AS  KindArabic,
    zChassisNo               AS  ChassisNo,
    zEngineNo                AS  EngineNo,
    zPrimaryVin              AS  PrimaryVin,
    zSecondaryVin            AS  SecondaryVin,
    zCountryCode             AS  CountryCode,
    zCountry                 AS  Country,
    zManufacturerCode        AS  ManufacturerCode,
    zManufacturer            AS  Manufacturer,
    zManufacturerAE          AS  ManufacturerArabic,
    zModelCode               AS  ModelCode,
    zHorsePower              AS  Horsepower,
    zAxles                   AS  NumberOfAxles,
    zCylinders	             AS  NumberOfCylinders,
    zWheels	                 AS  NumberOfWheels,
    zDoors	                 AS  NumberOfDoors,
    zPassengers	             AS  NumberOfPassengers,
    zEmptyWeight	         AS  EmptyWeight,
    zFullWeight	             AS  FullWeight,
    zMileage	             AS  Mileage,
    zCubicCapacity           AS  CubicCapacity,
    zCustomer	             AS  Customer,
    zCreationDate            AS  CreationDate,
    zCreationTime	         AS  CreationTime,
    zCreatedBy	             AS  CreatedBy,
    zInsuranceName           AS  InsuranceName,
    zInsuranceExp	         AS  InsuranceExpiry,
    zInsuranceKind	         AS  InsuranceKind,
    zInsuranceKindAE	     AS  InsuranceKindArabic,
    zInsurancePolicyNo	     AS  InsurancePolicyNumber,
    zMortgageDes	         AS  MortgageDescription,
    zMortgageRef	         AS  MortgageRef,
    zOwnerTcfNo	             AS  OwnerTcfNumber,
    zOwnerTcfAEName	         AS  OwnerTcfAEArabic,
    zOwnerTcfEnName	         AS  OwnerTcfEnglish,
    zModel	                 AS  Model,
    zModelAE                 AS  ModelArabic,
    zRegYear                 AS  RegistrationYear,
    zTypeCode                AS  TypeCode,
    zType                    AS  Type,
    zTypeAE                  AS  TypeArabic,
    zBodyColorCode           AS  BodyColorCode,
    zBodyColor               AS  BodyColor,
    zBodyColorAE             AS  BodyColorArabic,
    zGearCode                AS  GearCode,
    zGearType                AS  GearType,
    zGearTypeAE              AS  GearTypeArabic,
    zFuelCode                AS  FuelCode,
    zFuelType                AS  FuelType,
    zFuelTypeAE              AS  FuelTypeArabic,
    zSteeringCode            AS  SteeringCode,
    zSteeringSide            AS  SteeringSide,
    zSteeringSideAE          AS  SteeringSideArabic,
    zWeightCode              AS  WeightCode,
    zWeightDesc              AS  WeightDesc,
    zWeightDescAE            AS  WeightDescArabic,
    zRegDate                 AS  RegistrationDate,
    zRegExpDate              AS  RegistrationExpYear,
    zMfgYear                 AS  ManufacturerYear,
    zCustomCertificateNum    AS  CustomCertificateNumber,
    zCertificateDate         AS  CertificateDate,
    zCertificateCenterCode   AS  CertificateCenterCode,
    zCertificateCenter       AS  CertificateCenter,
    zRegistrationRemark      AS  RegistrationRemark,
    zNationalityCode         AS  NationalityCode,
    zNationality             AS  Nationality,
    zNationalityArabic       AS  NationalityArabic,
};

 entity MPurpose as projection on db.MPurpose;
 entity AnprCaptures as projection on db.AnprCaptures;
}

